language: generic

sudo: required
services: 
  - docker

before install: 
  - docker build -t jonny321/frontend -f Dockerfile.dev .

before script:
  - docker run -e CI=true jonny321/frontend npm run test

deploy:
   provider: elasticbeanstalk
   region: "us-east-2" 
   app: "frontend"
   env: "Frontend-env"
   bucket_name: "elasticbeanstalk-us-east-2-510767167582"
   bucket_path: "frontend"
   on:
      branch: main
   access_key_id: $AWS_access_key
   secret_access_key: $AWS_SECRET_KEY 
      
         

