language: generic

sudo: required
services: 
  - docker

before install: 
  - docker build -t jonny321/frontend -f Dockerfile.dev .

script:
  - - docker run USERNAME/docker-react npm run test -- --coverage

